#sg_all_access:
#  users:
#    - admin

sg_role_prometheus_perm:
  users:
    - prometheus_perm

sg_role_both_perms:
  users:
    - both_perms

sg_role_first_perm:
  users:
    - first_perm

sg_role_second_perm:
  users:
    - second_perm

